[package]
name = "td"
version = "0.1.0"
authors = ["Wim Berchmans <wim.berchmans@porphyrio.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
